# headers and icon 
title: Enrique Crespo Fernandez
info: phd cs @ UoB
icon-pic: assets/img/mandu_icon.png

# exclude these items when generated website in _site/index.html
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CV_README.md
  - DEPLOY_README.md

# Include .tex files for LaTeX CV generation
include:
  - cv.tex
